<?php
    session_start();
    //check for id
   if(isset($_GET['id'])){

    //Ensure that the id is accurate
    if(($_GET['id'] == $_SESSION['url_id']) || !empty($url_id) || ($url_id !== NULL) || (!empty($id) || ($id !== NULL))){
      //We passed
    }else{
        //Redirect back to the login page if id doesnt match the one generated by the system
      header("Location: ../../login");
    }
   }else{
       //Redirect if not logged in
       header("Location: ../../login");
   }        
            

?>